name: Python OpenCV Test

on:
    push:
        branches: [main]
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.x' # Thay '3.x' bằng phiên bản Python bạn muốn dùng

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install opencv-python

            - name: Run tests
              run: |
                  *
